### ISSUE TITLE
Missing 'numpy' module

### ISSUE THREAD

**Issue by ChewyPixels** [blurstudio/Simplex#114]
I'm getting this error when running the latest release:

# Error: ModuleNotFoundError: file \uvTransfer.py line 20: No module named 'numpy' #

**Comment by tbttfox** [comment]
Oh right, the numpy install. I forgot about that. I'll add that to the list, and put checks around the menu items that use it.

But first, let's talk about your message a little bit. When asking developers for help, it is better to provide too much information.  For instance, what OS are you using? And what version of Maya? Is it Python 2 or 3 (mostly for Maya 2022)?

Then there's something that Maya does that annoys the HECK out of me: They don't show the whole error! In the script editor History->Show Stack Trace needs to be checked. 

Luckily this time, I can see what the problem is without the whole error.

---

OK, now to numpy ...

If you're using Python 2 with Maya 2018 or newer on Windows, then get the numpy `.whl` file from here https://drive.google.com/drive/folders/0BwsYd1k8t0lEMjBCa2N1Z25KZXc?resourcekey=0-b4rufCHWfSqPrPzA731wfg

Then open a command prompt with admin access, cd to maya's bin directory (for me that's `C:\Program Files\Autodesk\Maya2019\bin`), and run these commands.  (If you're on maya 2022, it's `mayapy2.exe` instead)

```
mayapy.exe -m ensurepip --upgrade
mayapy.exe -m pip install <path-to-that-whl-file-you-downloaded>
```

If you're using any Maya with Python 3 on Windows, then I'm pretty sure you can just open an admin command prompt, cd to maya's bin directory, and run:

`mayapy.exe -m pip install numpy`

Unfortunately, I don't know how to handle this with Linux/MacOS.
